import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gradient-to-r from-[#b71e1e] to-[#7c8bff] text-white">
        <main className="flex min-h-screen flex-col items-center justify-center">
          <header className="sticky top-0 mt-4 flex w-screen items-center justify-center bg-gradient-to-r from-[#b71e1e] to-[#7c8bff]">
            <Link href="/" className="gap-2 text-4xl font-bold text-yellow-400">
              T3 Pokedex
            </Link>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
